[package]
name = "wavecore"
version.workspace = true
edition.workspace = true

[dependencies]
wavecore-html = { path = "../wavecore-html" }
wavecore-css = { path = "../wavecore-css" }
wavecore-style = { path = "../wavecore-style" }
wavecore-layout = { path = "../wavecore-layout" }
wavecore-render = { path = "../wavecore-render" }
