[package]
name = "wavecore-layout"
version.workspace = true
edition.workspace = true

[dependencies]
wavecore-dom = { path = "../wavecore-dom" }
wavecore-style = { path = "../wavecore-style" }
wavecore-text = { path = "../wavecore-text" }

[dev-dependencies]
wavecore-css = { path = "../wavecore-css" }
